version: "3.9"

services:
  face-auth-system:
    build: .
    container_name: face-auth-system
    restart: always
    ports:
      - "5000:5000"
    networks:
      - face-auth-net

networks:
  face-auth-net:
    driver: bridge
